### ISSUE TITLE
Ollama: Iterate Tool calls of failed attempts

### ISSUE THREAD

**Issue by ajshedivy** [chrishayuk/mcp-cli#11]
Related possibly: #9 

I've been experimenting with mcp-cli and its awesome!

One Issue I have been running into is that when using Ollama (llama3.2), I am unable to get the model to execute more that one tool call, and iterate on failed attempts. This seems to work fine in with gpt4o-mini

Here I have a simple demo with my custom Db2 for i MCP server: 

## Ollama - llama3.2
![image](https://github.com/user-attachments/assets/385a9b5a-63cb-4148-be70-5901a5a17974)

## OpenAI - gpt4o-mini
![image](https://github.com/user-attachments/assets/9dd932f8-3a7d-4f9c-9f32-dda529684c26)
![image](https://github.com/user-attachments/assets/25d63229-dacd-4ad6-8685-652728f20dee)

Apologies for small text, but here, gpt does a much better job at using the available tools to answer my input.

**Comment by chrishayuk** [comment]
tbh, llama 3.2 struggles, qwen does a better job, as does llama3.3.
i'll try and see if i can get llama3.2 to do a better job

**Comment by ajshedivy** [comment]
@chrishayuk Thanks for response! wasn't sure if this was a model limitation or apart of the client implementation. I can try the other models and compare responses

**Comment by ajshedivy** [comment]
Sounds good, lmk if you would like me to test anything!

**Comment by xbaicai08** [comment]
uv run --server
error: unexpected argument '--server' found

uv 0.5.7 (3ca155ddd 2024-12-06)

**Comment by chrishayuk** [comment]
uv run mcp-cli --server sqlite

i've updated the readme now, apologies.

**Comment by chrishayuk** [comment]
this should be okay now, but you will get better results from qwen rather than llama3.2
