### ISSUE TITLE
Tip to allow all LLM usages

### ISSUE THREAD

**Issue by AtheeSouhait** [chrishayuk/mcp-cli#4]
Great work, works well!
You can improve the solution by integrate all llms: you can use andrewng aisuite
[https://github.com/andrewyng/aisuite](https://github.com/andrewyng/aisuite) to do so without effort.
Thanks for your work!

**Comment by chrishayuk** [comment]
that's a really good shout, i was planning to put litellm in at some point, but i've been meaning to look andrew ng's ai suite.  i purposely didn't do that in this version of the tool.  as the tool exists to serve the video.   i feel that if i introduce too many abstraction layers in a video, it's hard to see what i'm doing, and it's hard for others to learn the protocol.  so for this version i decided to stick with native ollama, and native openai.   but i will add support either through aisuite or litellm, so appreciate the suggestion

**Comment by chrishayuk** [comment]
so i took a look at it, but aisuite doesn't support function calling, and their pr strategy is a little slow, someone pr'd the fix for it a while ago, but it's never been merged, but i'll keep an eye on it, thanks for the thought
