### ISSUE TITLE
Support for running multiple servers

### ISSUE THREAD

**Issue by huseyint** [chrishayuk/mcp-cli#7]
is it possible to run multiple servers:

```
uv run main.py --server puppeteer --server filesystem --provider ollama --model llama3.2
```

**Comment by chrishayuk** [comment]
that is an extremely good point...
let me fix that

**Comment by scalVeerne** [comment]
Really neeed that

**Comment by mix1009** [comment]
here is my PR

https://github.com/chrishayuk/mcp-cli/pull/13

**Comment by chrishayuk** [comment]
superstar thank you @mix1009
